spring:
  application:
    name: consumer-service-v2
  # zipkin:
  #   base-url: http://127.0.0.1:9411/
  # sleuth:
  #   sampler:
  #     rate: 1
  # boot:
  #   admin:
  #     client:
  #       url: http://127.0.0.1:90

eureka:
  client:
    service-url:
      defaultZone: http://ixiaoyu2:ixiaoyu2@127.0.0.1:7000/eureka
    healthcheck:
      enabled: true


logging:
  level:
    com.ixiaoyu2: debug

ribbon:
  # 连接超时时间(ms)
  ConnectTimeout: 1000
  # 业务逻辑超时时间(ms)
  ReadTimeout: 2000
  # 同一台实例最大重试次数,不包括首次调用
  MaxAutoRetries: 1
  # 重试负载均衡其他的实例最大重试次数,不包括首次调用
  MaxAutoRetriesNextServer: 1
  # 是否所有操作都重试
  OkToRetryOnAllOperations: false

feign:
  hystrix:
    enabled: true


management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
hystrix:
  dashboard:
    proxy-stream-allow-list: localhost
  command:
    default:
      execution:
        isolution:
          # 隔离策略，默认是Thread, 可选Thread｜Semaphore
          # thread 通过线程数量来限制并发请求数，可以提供额外的保护，但有一定的延迟。一般用于网络调用
          # semaphore 通过semaphore count来限制并发请求数，适用于无网络的高并发请求
          strategy: SEMAPHORE

myconfig-version: v3